repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/Scony/gdtoolkit
    rev: 4.3.4
    hooks:
      - id: gdformat
        files: \.gd$
